project:
  type: website
  output-dir: docs   # 👈 aqui que faz o site ir para /docs

website:
  title: "Wilhan Valasco"
  navbar:
    left:
      - href: index.qmd
        text: "Início"
      - href: about.qmd
        text: "Sobre"
      - href: projects.qmd
        text: "Projetos"
      - href: codes.qmd
        text: "Códigos em R"
      - href: contact.qmd
        text: "Contato"

format:
  html:
    theme: cosmo
    css: styles.css
